import json

nb = {
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {"provenance": []},
    "kernelspec": {"name": "python3", "display_name": "Python 3"}
  },
  "cells": [
    {
      "cell_type": "markdown",
      "source": [
        "# YoutubeDownloader - Free Cloud Version\n",
        "Google Colab does not allow auto-running for security reasons. Please click the **Play (▶️)** button below to start the server. \n",
        "A stylish popup will appear with your clean public link once it's ready!"
      ],
      "metadata": {"id": "md1"}
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {"id": "code1"},
      "outputs": [],
      "source": [
        "!git clone https://github.com/RashidKhanApDev/YoutubeDownloader.git > /dev/null 2>&1\n",
        "%cd YoutubeDownloader\n",
        "!pip install -r requirements.txt > /dev/null 2>&1\n",
        "\n",
        "import subprocess\n",
        "import time\n",
        "import re\n",
        "from IPython.display import display, HTML\n",
        "\n",
        "print(\"Installing High-Speed Cloudflare Tunnel...\")\n",
        "subprocess.run([\"wget\", \"-q\", \"https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb\"])\n",
        "subprocess.run([\"dpkg\", \"-i\", \"cloudflared-linux-amd64.deb\"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)\n",
        "\n",
        "print(\"Starting Server... Please wait a moment...\")\n",
        "subprocess.Popen([\"python\", \"-m\", \"uvicorn\", \"main:app\", \"--host\", \"0.0.0.0\", \"--port\", \"8000\"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)\n",
        "time.sleep(3)\n",
        "\n",
        "print(\"Generating Clean Public Link...\")\n",
        "cf_process = subprocess.Popen([\"cloudflared\", \"tunnel\", \"--url\", \"http://localhost:8000\"], stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)\n",
        "\n",
        "url = \"\"\n",
        "for line in cf_process.stdout:\n",
        "    match = re.search(r\"https://[a-zA-Z0-9-]+\\.trycloudflare\\.com\", line)\n",
        "    if match:\n",
        "        url = match.group(0)\n",
        "        break\n",
        "\n",
        "print(\"\\n=============================================\")\n",
        "print(\"✅ SERVER IS READY!\")\n",
        "print(\"👉 Link:\", url)\n",
        "print(\"=============================================\\n\")\n",
        "\n",
        "html_code = f\"\"\"\n",
        "<style>\n",
        ".custom-modal-overlay {{\n",
        "    position: fixed;\n",
        "    top: 0; left: 0; right: 0; bottom: 0;\n",
        "    background: rgba(0, 0, 0, 0.6);\n",
        "    display: flex;\n",
        "    align-items: center;\n",
        "    justify-content: center;\n",
        "    z-index: 9999;\n",
        "    backdrop-filter: blur(5px);\n",
        "}}\n",
        ".custom-modal {{\n",
        "    background: linear-gradient(135deg, #0ba360 0%, #3cba92 100%);\n",
        "    padding: 35px 30px;\n",
        "    border-radius: 20px;\n",
        "    box-shadow: 0 15px 35px rgba(0,0,0,0.3);\n",
        "    text-align: center;\n",
        "    color: white;\n",
        "    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n",
        "    max-width: 450px;\n",
        "    width: 90%;\n",
        "    animation: popIn 0.5s cubic-bezier(0.175, 0.885, 0.32, 1.275);\n",
        "}}\n",
        "@keyframes popIn {{\n",
        "    0% {{ transform: scale(0.8); opacity: 0; }}\n",
        "    100% {{ transform: scale(1); opacity: 1; }}\n",
        "}}\n",
        ".custom-modal h2 {{\n",
        "    margin-top: 0; color: white; font-weight: 800; letter-spacing: 1px; font-size: 24px;\n",
        "}}\n",
        ".custom-input-group {{\n",
        "    margin: 25px 0;\n",
        "    background: rgba(255,255,255,0.2);\n",
        "    padding: 15px;\n",
        "    border-radius: 12px;\n",
        "    border: 1px solid rgba(255,255,255,0.3);\n",
        "}}\n",
        ".custom-input-group p {{\n",
        "    margin: 0 0 10px 0; font-size: 15px; font-weight: 700; opacity: 0.95;\n",
        "}}\n",
        ".custom-input-group input {{\n",
        "    width: 90%;\n",
        "    padding: 12px;\n",
        "    border: none;\n",
        "    border-radius: 8px;\n",
        "    text-align: center;\n",
        "    font-weight: bold;\n",
        "    color: #0ba360;\n",
        "    background: white;\n",
        "    font-size: 17px;\n",
        "}}\n",
        ".copy-btn {{\n",
        "    background: #ffffff;\n",
        "    color: #0ba360;\n",
        "    border: none;\n",
        "    padding: 14px 28px;\n",
        "    border-radius: 50px;\n",
        "    font-weight: 800;\n",
        "    font-size: 16px;\n",
        "    cursor: pointer;\n",
        "    margin-top: 15px;\n",
        "    transition: all 0.3s ease;\n",
        "    box-shadow: 0 4px 15px rgba(0,0,0,0.15);\n",
        "}}\n",
        ".copy-btn:hover {{\n",
        "    transform: translateY(-3px);\n",
        "    box-shadow: 0 6px 20px rgba(0,0,0,0.25);\n",
        "}}\n",
        ".close-btn {{\n",
        "    margin-top: 20px;\n",
        "    cursor: pointer;\n",
        "    font-size: 14px;\n",
        "    opacity: 0.8;\n",
        "    text-decoration: underline;\n",
        "    font-weight: 600;\n",
        "}}\n",
        ".close-btn:hover {{ opacity: 1; }}\n",
        "</style>\n",
        "\n",
        "<div class=\"custom-modal-overlay\" id=\"myModal\">\n",
        "    <div class=\"custom-modal\">\n",
        "        <h2>✅ SERVER IS READY</h2>\n",
        "        <p style=\"font-size: 15px; opacity: 0.9;\">Your cloud downloader is running successfully!</p>\n",
        "        \n",
        "        <div class=\"custom-input-group\">\n",
        "            <p>🔗 PUBLIC LINK:</p>\n",
        "            <input type=\"text\" id=\"linkText\" value=\"{url}\" readonly>\n",
        "        </div>\n",
        "        \n",
        "        <button class=\"copy-btn\" onclick=\"copyDetails()\">📋 Copy Link</button>\n",
        "        <div class=\"close-btn\" onclick=\"document.getElementById('myModal').style.display='none'\">Dismiss</div>\n",
        "    </div>\n",
        "</div>\n",
        "\n",
        "<script>\n",
        "function copyDetails() {{\n",
        "    var link = document.getElementById(\"linkText\").value;\n",
        "    var btn = document.querySelector(\".copy-btn\");\n",
        "    \n",
        "    if(navigator.clipboard && window.isSecureContext) {{\n",
        "        navigator.clipboard.writeText(link).then(function() {{\n",
        "            btn.innerHTML = \"✅ Copied Successfully!\";\n",
        "            setTimeout(function() {{ btn.innerHTML = \"📋 Copy Link\"; }}, 3000);\n",
        "        }});\n",
        "    }} else {{\n",
        "        var dummy = document.createElement(\"textarea\");\n",
        "        document.body.appendChild(dummy);\n",
        "        dummy.value = link;\n",
        "        dummy.select();\n",
        "        document.execCommand(\"copy\");\n",
        "        document.body.removeChild(dummy);\n",
        "        btn.innerHTML = \"✅ Copied Successfully!\";\n",
        "        setTimeout(function() {{ btn.innerHTML = \"📋 Copy Link\"; }}, 3000);\n",
        "    }}\n",
        "}}\n",
        "</script>\n",
        "\"\"\"\n",
        "display(HTML(html_code))\n",
        "\n",
        "# Keep tunnel alive\n",
        "cf_process.wait()\n"
      ]
    }
  ]
}

with open('YoutubeDownloader.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=2)
